# Generated by Django 5.1.7 on 2025-04-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_last_login_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pending_tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
