# Generated by Django 5.1.7 on 2025-04-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_price'),
        ('staff', '0002_staff_last_login_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flights', to='staff.staff'),
        ),
    ]
