# Generated by Django 5.1.7 on 2025-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
