# Generated by Django 5.1.7 on 2025-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
